# Generated by Django 5.2.6 on 2025-12-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_books_quantity_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('canceled', 'Отменен')], default='new', max_length=20),
        ),
    ]
